FROM nodered/node-red-docker:rpi
MAINTAINER kevin.viet@gmail.com

RUN    npm install node-red-contrib-openhab2 \
    && npm install node-red-contrib-bigtimer \
    && npm install node-red-contrib-ramp-thermostat \
    && npm install node-red-contrib-fsm



